import base64
import requests
from fastapi import HTTPException, status
from backend.databases.connection import SessionLocal
from backend.databases.models import User, AnalysisRun


def push_to_github_repository(user_id: str, analysis_id: str, repo_name: str, private: bool):
    with SessionLocal() as session:
        user = session.query(User).filter(User.id == user_id).first()
        if not user or not user.github_token:
            raise HTTPException(status_code=400, detail="GitHub account link missing! Connect first.")
        github_token = user.github_token

        
        analysis_data = session.query(AnalysisRun).filter(
            AnalysisRun.id == analysis_id, 
            AnalysisRun.user_id == user_id
        ).first()
        
        if not analysis_data:
            raise HTTPException(status_code=404, detail="Requested AI analysis code report not found in records.")
            
        code_text = analysis_data.optimized_code
        readme_text = analysis_data.readme_content or analysis_data.explanation or "# AI Generated Code"
        language = analysis_data.language

    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    repo_payload = {
        "name": repo_name,
        "private": private,
        "description": "Optimized code generated by AI Powered Coding Assistant."
    }
    create_repo_url = "https://api.github.com/user/repos"
    repo_response = requests.post(create_repo_url, json=repo_payload, headers=headers)
    
    if repo_response.status_code not in [201, 200]:
        raise HTTPException(
            status_code=400,
            detail=f"GitHub repository creation failed: {repo_response.json()}"
        )
        
    repo_data = repo_response.json()
    owner_username = repo_data["owner"]["login"]
    
    ext_map = {"python": ".py", "javascript": ".js", "typescript": ".ts", "java": ".java","cpp":".cpp","c":".c"}
    code_filename = f"main{ext_map.get(language.lower(), '.txt')}"
    
    def to_b64(text: str) -> str:
        return base64.b64encode(text.encode('utf-8')).decode('utf-8')
        
    base_contents_url = f"https://api.github.com/repos/{owner_username}/{repo_name}/contents"
    
    readme_res = requests.put(
        f"{base_contents_url}/README.md",
        json={"message": "Add README", "content": to_b64(readme_text)},
        headers=headers
    )
    code_res = requests.put(
        f"{base_contents_url}/{code_filename}",
        json={"message": f"Add optimized source code in {code_filename}", "content": to_b64(code_text)},
        headers=headers
    )

    if readme_res.status_code not in [201, 200]:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Repository created, but README upload failed: {readme_res.json()}"
        )

    if code_res.status_code not in [201, 200]:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Repository created, but code upload failed: {code_res.json()}"
        )
    
    return {
        "success": True,
        "repo_url": repo_data.get("html_url"),
        "message": "Optimized code and README pushed to GitHub successfully."
    }
