import base64
import re

import requests
from fastapi import HTTPException, status

from backend.databases.connection import SessionLocal
from backend.databases.models import AnalysisRun, User


def push_to_github_repository(user_id: str, analysis_id: str, repo_name: str, private: bool):
    repo_name = repo_name.strip()

    if not repo_name:
        raise HTTPException(status_code=400, detail="Repository name is required.")

    if not re.fullmatch(r"[A-Za-z0-9._-]+", repo_name):
        raise HTTPException(
            status_code=400,
            detail="Repository name can contain only letters, numbers, dots, underscores, and hyphens.",
        )

    with SessionLocal() as session:
        user = session.query(User).filter(User.id == user_id).first()
        if not user or not user.github_token:
            raise HTTPException(status_code=400, detail="GitHub account link missing. Connect GitHub first.")

        analysis_data = session.query(AnalysisRun).filter(
            AnalysisRun.id == analysis_id,
            AnalysisRun.user_id == user_id,
        ).first()

        if not analysis_data:
            raise HTTPException(status_code=404, detail="Selected analysis run was not found.")

        github_token = user.github_token
        code_text = analysis_data.optimized_code or analysis_data.fixed_code or analysis_data.original_code
        readme_text = analysis_data.readme_content or analysis_data.explanation or "# AI Generated Code"
        language = analysis_data.language or "txt"

    if not code_text:
        raise HTTPException(status_code=400, detail="No code found for the selected analysis run.")

    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    repo_payload = {
        "name": repo_name,
        "private": private,
        "description": "Optimized code generated by AI Powered Coding Assistant.",
        "auto_init": False,
    }

    try:
        repo_response = requests.post(
            "https://api.github.com/user/repos",
            json=repo_payload,
            headers=headers,
            timeout=30,
        )
    except requests.RequestException as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Could not reach GitHub while creating repository: {exc}",
        ) from exc

    if repo_response.status_code not in [201, 200]:
        raise HTTPException(
            status_code=400,
            detail=f"GitHub repository creation failed: {repo_response.text}",
        )

    repo_data = repo_response.json()
    owner_username = repo_data["owner"]["login"]

    ext_map = {
        "python": ".py",
        "javascript": ".js",
        "typescript": ".ts",
        "java": ".java",
        "cpp": ".cpp",
        "c": ".c",
    }
    code_filename = f"main{ext_map.get(language.lower(), '.txt')}"

    def to_b64(text: str) -> str:
        return base64.b64encode(text.encode("utf-8")).decode("utf-8")

    base_contents_url = f"https://api.github.com/repos/{owner_username}/{repo_name}/contents"

    try:
        readme_res = requests.put(
            f"{base_contents_url}/README.md",
            json={"message": "Add README", "content": to_b64(readme_text)},
            headers=headers,
            timeout=30,
        )
        code_res = requests.put(
            f"{base_contents_url}/{code_filename}",
            json={"message": f"Add optimized source code in {code_filename}", "content": to_b64(code_text)},
            headers=headers,
            timeout=30,
        )
    except requests.RequestException as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Could not reach GitHub while uploading files: {exc}",
        ) from exc

    if readme_res.status_code not in [201, 200]:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Repository created, but README upload failed: {readme_res.text}",
        )

    if code_res.status_code not in [201, 200]:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Repository created, but code upload failed: {code_res.text}",
        )

    return {
        "success": True,
        "repo_url": repo_data.get("html_url"),
        "message": "Optimized code and README pushed to GitHub successfully.",
    }
